"""empty message

Revision ID: 3e0a5c1edae7
Revises: 563770606601
Create Date: 2015-11-05 13:51:51.740040

"""

# revision identifiers, used by Alembic.
revision = '3e0a5c1edae7'
down_revision = '563770606601'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collab_context', sa.Column('experiment_id', sa.String(), nullable=True))
    op.drop_column('collab_context', 'experiment_configuration')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collab_context', sa.Column('experiment_configuration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('collab_context', 'experiment_id')
    ### end Alembic commands ###
