"""empty message

Revision ID: 563770606601
Revises: 438b972add0f
Create Date: 2015-11-05 10:52:33.745102

"""

# revision identifiers, used by Alembic.
revision = '563770606601'
down_revision = '438b972add0f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collab_context', 'context_id',
               existing_type=sa.INTEGER(),
               type_=sa.String())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collab_context', 'context_id',
               existing_type=sa.String(),
               type_=sa.INTEGER())
    ### end Alembic commands ###
